# Generated by Django 5.0.1 on 2024-03-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilevariantmodel',
            name='variant_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
