# Generated by Django 5.0.1 on 2024-03-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0002_mobilevariantmodel_variant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilevariantmodel',
            old_name='rom',
            new_name='storage',
        ),
    ]
