# Generated by Django 5.0.1 on 2024-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0003_rename_rom_mobilevariantmodel_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_desc',
            field=models.TextField(),
        ),
    ]
