# Generated by Django 5.0.1 on 2024-03-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0004_alter_productmodel_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilevariantmodel',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
