# Generated by Django 5.0.1 on 2024-03-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('SellerApp', '0005_mobilevariantmodel_color'),
        ('UserApp', '0004_rename_mobile_variant_id_cartmodel_variant_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileVariantModel',
            new_name='ProductVariantModel',
        ),
    ]
