# Generated by Django 5.0.4 on 2024-05-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0008_alter_productvariantmodel_apps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantmodel',
            name='apps',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='battery',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='camera',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='display',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='display_size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='launch_year',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='operating_system',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='original_price',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='processor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='ram',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='selling_price',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='sound_output',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='storage',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
