# Generated by Django 5.0.1 on 2024-03-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0005_mobilevariantmodel_color'),
        ('UserApp', '0002_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='mobile_variant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerApp.mobilevariantmodel'),
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='mobile_variant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerApp.mobilevariantmodel'),
        ),
    ]
