# Generated by Django 5.0.1 on 2024-03-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_remove_cartmodel_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='mobile_variant_id',
            new_name='variant_id',
        ),
        migrations.RenameField(
            model_name='wishlistmodel',
            old_name='mobile_variant_id',
            new_name='variant_id',
        ),
    ]
