# Generated by Django 5.0.1 on 2024-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_rename_mobile_variant_id_cartmodel_variant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
