# Generated by Django 5.0.1 on 2024-03-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_usermodel_dob_usermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressmodel',
            name='landmark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='locality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
