# Generated by Django 5.0.1 on 2024-03-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0007_productvariantmodel_apps_and_more'),
        ('UserApp', '0006_alter_useraddressmodel_landmark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingordermodel',
            old_name='date',
            new_name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='shoppingordermodel',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='shoppingordermodel',
            name='product_id',
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='address_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='landmark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='locality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='name_in_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingordermodel',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='orderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.shoppingordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SellerApp.productvariantmodel')),
            ],
            options={
                'db_table': 'products in order',
            },
        ),
    ]
